apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem